### ISSUE TITLE
Comment Sections

### ISSUE THREAD

**Issue by brandonijones** [EMU-COSC471-W22/idea-website#17]
As a user of the IDEA, I would like to comment on art pieces I find interesting. If I make a mistake on a comment, comment accidentally, or just don't want my comment up anymore, I should have the option to delete it whenever I would like.

**Acceptance Tests/Constraints**
1. Users can only comment once they are logged in
2. Each comment should display the name and username
3. Users can only delete comments they made

**Tasks**
- [x] Create a comments table associated with an art piece and a username
- [x] Validate that a user is logged in before they can comment
- [x] Add a delete button on the comments made by the currently logged in user
- [x] Display first name, last name, and username on each comment
- [x] Validate that the user is not submitting an empty comment
