### ISSUE TITLE
Account Registration

### ISSUE THREAD

**Issue by brandonijones** [EMU-COSC471-W22/idea-website#18]
As a user of the IDEA, I would like to make an account so that I can request my own art pieces and make comments. 

**Acceptance Constratins/Criteria**
1. Basic form validation (no fields left blank, valid email, valid password)
2. Ensure that the username entered is not already taken by another user

**Tasks**
- [x] Add user to database upon successful registration
- [x] Validate a unique username
- [x] General form validation
