### ISSUE TITLE
Administration Privileges 

### ISSUE THREAD

**Issue by brandonijones** [EMU-COSC471-W22/idea-website#19]
As an admin for the IDEA website, I need to be able to access all the art and accounts on the website. I need to be able to effectively moderate the website by having privileges to update and delete accounts, art pieces, and comments.

**Acceptance Criteria**
1. Admins can delete any comment
2. Admins can delete any account
3. Admins can delete any art piece
4. Admins can change the type of account for any particular user after clicking on the account type
5. Admins can accept or decline art submitted by users

**Tasks**
- [x] Verify user type before being able to access the admin page or perform an administrative action
- [x] Include delete buttons for art 
- [x] Include delete buttons for accounts
- [x] Make a simple form to edit account type
- [x] Make sure delete buttons show for all comments if an admin is logged in.
